version: '3'

services:
  web:
    build: .
    command: uvicorn app.main:app --reload --host 0.0.0.0
    volumes:
      - ./:/code
      - ./proxy:/etc/squid/
    ports:
      - 8000:8000
    env_file:
      - .env.dev

  proxy:
    image: ubuntu/squid:5.2-22.04_beta
    volumes:
      - ./proxy:/etc/squid/
    ports:
      - "8080:3128"
    restart: always